version: "3.8"
services:
  catalog-service:
    depends_on:
      - bookshop-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  bookshop-postgres:
    image: "postgres:16.2"
    container_name: "bookshop-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
