version: '3.8'
services:
  catalog-service:
    depends_on:
      - bookshop-postgres
    image: 'catalog-service'
    container_name: 'catalog-service'
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  order-service:
    depends_on:
      - bookshop-postgres
    image: 'order-service'
    container_name: 'order-service'
    ports:
      - 9002:9002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002

      - BOOKSHOP_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_R2DBC_URL=r2dbc:postgresql://bookshop-postgres:5432/bookshopdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_order

  edge-service:
    depends_on:
      - bookshop-redis
    image: 'edge-service'
    container_name: 'edge-service'
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000

      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATA_REDIS_HOST=bookshop-redis

  bookshop-postgres:
    image: 'postgres:16.2'
    container_name: 'bookshop-postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  bookshop-redis:
    image: 'redis:7.2.4'
    container_name: 'bookshop-redis'
    ports:
      - 6379:6379
